# Generated by Django 4.2 on 2025-05-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(null=True, upload_to='pokemon_images'),
        ),
    ]
